### PR TITLE
Update SDK and dependencies

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by sebaslogen** [comment]
Thanks for the contribution! :)

The automated tests on Travis CI fail because the configuration for the CI environment was not updated.
Can you please update the [.travis.yml](https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/.travis.yml) file in the root to use android-24 and build-tools to accommodate your changes?

**Comment by nightscape** [comment]
Ah, had forgotten about Travis ;)
Fixed that and also cleaned history a little.
Now it should hopefully be good to go :+1:

**Comment by sebaslogen** [comment]
Super, thanks for the update effort!

**Comment by nightscape** [comment]
Thanks for creating that tutorial, probably saved me hours to figure it out by myself :D

**Pull request merged**
